[package]
name = "snowflake"
version = "0.1.0"
authors = ["Karl Bateman <karl.bateman@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.4.2"
